# Module1: Basics of Python and Ethical Hacking

In [3]:
print("Hello World")

Hello World

### Variables in Python

In [1]:
name = "Hacker"
age = 21
rating = 4.9
is_Active = True 

tools = ["nmap", "wireshack", "brup"]

#What will be the output of? 
result = name+str(age) 
print(result)

print(name, age, rating, is_Active, tools, sep="\n")

#Accessing last element of the list 
print(tools[::-1])

#first to last 
print(tools[:1])

#tuple 

myTuple = ("Python", 1, "Hello", [1,2,3,4,5])

print(myTuple[::-1])

#dictionary 
profile = {
    "name": "Hacker",
    "age": 21,
    "tools": ["nmap", "wireshark"]
}
print(profile["name"])   # Output: Hacker
print(profile["tools"][1])  # Output: wireshark (list indexing inside dictionary)



for key in profile:
    print(key, "=>", profile[key])  # key and corresponding value

Hacker21
Hacker
21
4.9
True
['nmap', 'wireshack', 'brup']
['brup', 'wireshack', 'nmap']
['nmap']
([1, 2, 3, 4, 5], 'Hello', 1, 'Python')
Hacker
wireshark
name => Hacker
age => 21
tools => ['nmap', 'wireshark']

In [4]:
#loops in python 

#right angled triangle * pattern 

'''
* 
** 
*** 
****
*****
'''

n =5 
for i in range(1,n+1): 
    print("*"*i)

'''
    Inverted pattern
    *****
    ****
    ***
    **
    *


'''
print()
print()

for i in range(n,0, -1): 
    print("*"*i)

*
**
***
****
*****


*****
****
***
**
*

In [ ]:
    #    * 
    #   ***
    #  *****
    # *******

IndentationError: expected an indented block after 'for' statement on line 7 (134038069.py, line 8)

In [12]:
row = 4
for i in range(1, row+1):
    print(" "*(n-i)+"*"* (2*i-1))

    *
   ***
  *****
 *******

In [13]:
# Binary Hacker Triangle 

'''

0 
1 0 
0 1 0 
1 0 1 0 
0 1 0 1 0 

'''

rows = int(input("Enter the row value"))
for i in range(1, row+1): 
    for j in range(1,i+1): 
        print((i+j)%2,end="")
    print()

0
10
010
1010

In [15]:
#Functions in python 

''' 
   Calculate the area of squire using funciton 
'''

def calculateArea(a,b): 
    return a*b


a = int(input("Enter the value of a"))
b = int(input("Enter the value of b"))

#call funciton 

calculateArea(a,b)


#args and kwargs 


def my_function(a,b,c): 
    print(a,b,c)
    
args= (1,5,7)
my_function(*args)

1 5 7

In [20]:
#STRING 

message = " I am a ethical hacker"

words = message.split()

print(message)
print(words)

joined = "->".join(words)
print(joined)

print(message.upper())
print(message.lower())

 I am a ethical hacker
['I', 'am', 'a', 'ethical', 'hacker']
I->am->a->ethical->hacker
 I AM A ETHICAL HACKER
 i am a ethical hacker

# Permutation and Combination 

## Itertool module: 
- Iterate tool module helps to generate permutation and combinations using nested loops 
- **product()** all possible combinations i.e. Cartician Product. It helps to generate multiple password combinations

In [24]:
import itertools

char = 'ab1abc'
length = 3 

for combo in itertools.product(char, repeat=length): 
    print(''.join(combo))

aaa
aab
aa1
aaa
aab
aac
aba
abb
ab1
aba
abb
abc
a1a
a1b
a11
a1a
a1b
a1c
aaa
aab
aa1
aaa
aab
aac
aba
abb
ab1
aba
abb
abc
aca
acb
ac1
aca
acb
acc
baa
bab
ba1
baa
bab
bac
bba
bbb
bb1
bba
bbb
bbc
b1a
b1b
b11
b1a
b1b
b1c
baa
bab
ba1
baa
bab
bac
bba
bbb
bb1
bba
bbb
bbc
bca
bcb
bc1
bca
bcb
bcc
1aa
1ab
1a1
1aa
1ab
1ac
1ba
1bb
1b1
1ba
1bb
1bc
11a
11b
111
11a
11b
11c
1aa
1ab
1a1
1aa
1ab
1ac
1ba
1bb
1b1
1ba
1bb
1bc
1ca
1cb
1c1
1ca
1cb
1cc
aaa
aab
aa1
aaa
aab
aac
aba
abb
ab1
aba
abb
abc
a1a
a1b
a11
a1a
a1b
a1c
aaa
aab
aa1
aaa
aab
aac
aba
abb
ab1
aba
abb
abc
aca
acb
ac1
aca
acb
acc
baa
bab
ba1
baa
bab
bac
bba
bbb
bb1
bba
bbb
bbc
b1a
b1b
b11
b1a
b1b
b1c
baa
bab
ba1
baa
bab
bac
bba
bbb
bb1
bba
bbb
bbc
bca
bcb
bc1
bca
bcb
bcc
caa
cab
ca1
caa
cab
cac
cba
cbb
cb1
cba
cbb
cbc
c1a
c1b
c11
c1a
c1b
c1c
caa
cab
ca1
caa
cab
cac
cba
cbb
cb1
cba
cbb
cbc
cca
ccb
cc1
cca
ccb
ccc

# Password and Combinations

| Charset                   | Size | Description                  |
|---------------------------|------|------------------------------|
| Digit only (0–9)          | 10   | Numbers from 0 to 9          |
| Lowercase Char (a–z)      | 26   | Lowercase English letters    |
| Uppercase Char (A–Z)      | 26   | Uppercase English letters    |
| Alpha + Numeric           | 36   | a–z and 0–9                  |
| AlphaNumeric + Uppercase | 62   | a–z, A–Z, and 0–9            |

# We are trying to attack the password then what can be the combinations 

| Password Length | Character Set       | Set Size | Total Combinations      | Estimated Time          |
|-----------------|---------------------|----------|--------------------------|--------------------------|
| 3               | Digits (0–9)         | 10       | 10³ = 1,000              | 1 second                 |
| 4               | Lowercase (a–z)      | 26       | 26⁴ = 456,976            | ~7.6 minutes             |
| 5               | Lowercase (a–z)      | 26       | 26⁵ = 11,881,376         | ~3.3 hours               |
| 6               | Lowercase (a–z)      | 26       | 26⁶ = 308,915,776        | ~3.6 days                |
| 6               | Digits (0–9)         | 10       | 10⁶ = 1,000,000          | ~16.7 minutes            |
| 6               | Alphanumeric (a–z,0–9) | 36     | 36⁶ = 2,176,782,336      | ~25 days                |
| 6               | Lower + Upper (a–z, A–Z) | 52   | 52⁶ = 19,770,609,664     | ~229 days               |
| 6               | All ASCII (a–z, A–Z, 0–9, symbols) | 95 | 95⁶ ≈ 735 billion | ~23 years               |
| 7               | Lowercase (a–z)      | 26       | 26⁷ = 8,031,810,176      | ~93 days                |
| 8               | Digits only (0–9)    | 10       | 10⁸ = 100,000,000        | ~27.8 hours             |
| 8               | Lowercase (a–z)      | 26       | 26⁸ = 208,827,064,576    | ~6.6 years              |
| 8               | Alphanumeric (a–z,0–9) | 36     | 36⁸ ≈ 2.8 trillion        | ~89 years               |
| 8               | All ASCII (95 chars) | 95       | 95⁸ ≈ 6.6 quadrillion     | ~209,000 years          |
| 10              | Digits (0–9)         | 10       | 10¹⁰ = 10,000,000,000    | ~115 days               |
| 10              | Lowercase (a–z)      | 26       | 26¹⁰ ≈ 1.4 x 10¹⁴         | ~4,456 years            |
| 10              | Alphanumeric         | 36       | 36¹⁰ ≈ 3.6 x 10¹⁵         | ~114,000 years          |
| 10              | Full ASCII (95)      | 95       | 95¹⁰ ≈ 5.99 x 10¹⁹        | ~1.9 billion years      |

DatabaseError: 1205 (HY000): Lock wait timeout exceeded; try restarting transaction

In [1]:
from base64 import encode
import mysql.connector
import hashlib

#connect to mysql 
conn = mysql.connector.connect(
    host = "localhost", 
    user = "root", 
    password = "S@r0ji@m17",
    database = "MachineLearning"
)


cur = conn.cursor()

password = 'S@r0j12234'
hashed_password = hashlib.sha256(password.encode()).hexdigest()  # Store the hash result

cur.execute("INSERT INTO Users(UserName, Password) VALUES (%s, %s)", ('Saroj12', hashed_password))

conn.commit()

# cur.execute("SELECT * FROM Users")

for cursor in cur: 
    print(cursor)